"""Generate synchronized manuscript and deliverable reports from metric artifacts."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
MANUSCRIPT_DIR = ROOT / "manuscript"
REPORTS_DIR = ROOT / "reports"


def _sha(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _read(path: str) -> pd.DataFrame:
    return pd.read_csv(ROOT / path)


def _metric(df: pd.DataFrame, row_key: str, col: str):
    row = df[df.iloc[:, 0] == row_key]
    return row.iloc[0][col] if not row.empty and col in row.columns else "not_available"


def main() -> None:
    MANUSCRIPT_DIR.mkdir(exist_ok=True)
    REPORTS_DIR.mkdir(exist_ok=True)

    table1 = _read("tables/table1_track_error_vs_baselines.csv")
    case = _read("tables/table_case_study_track_error.csv")
    hum = _read("tables/table2_humanitarian_impact.csv")
    abl = _read("tables/table3_ablations.csv")
    cf = _read("tables/table_counterfactual_outcomes.csv")
    forecast = _read("tables/table_forecast_performance_audit.csv")
    foundation = _read("tables/table_foundation_model_training.csv")
    dataset_audit = json.loads((ROOT / "metrics/dataset_integrity/dataset_integrity_audit.json").read_text())
    calibration_audit = json.loads((ROOT / "metrics/foundation/calibration_consistency_audit.json").read_text())

    persistence_case = case[case["model"] == "Persistence"].iloc[0]
    gno_case = case[case["model"] == "GNO+DynGNN"].iloc[0]
    selected_epoch = int(foundation.iloc[0]["epoch"])
    selection_score = float(foundation.iloc[0]["selection_score"])

    child_mape = _metric(hum, "exposed_children_MAPE", "STORM-CARE-M3")
    school_auc = _metric(hum, "school_disruption_AUC", "STORM-CARE-M3")
    hospital_mae = _metric(hum, "hospital_accessibility_MAE", "STORM-CARE-M3")
    priority_rho = _metric(hum, "recovery_priority_spearman", "STORM-CARE-M3")

    full_abl = abl[abl["variant"] == "STORM-CARE full"].iloc[0]
    no_transport = abl[abl["variant"] == "no_transport_edges"].iloc[0]
    static_graph = abl[abl["variant"] == "static_graph_no_propagation"].iloc[0]

    baseline_cf = cf[cf["scenario"] == "baseline"].iloc[0]
    early_cf = cf[cf["scenario"] == "earlier_evacuation"].iloc[0]
    delayed_cf = cf[cf["scenario"] == "delayed_evacuation"].iloc[0]

    manuscript = f"""# STORM-CARE-FM Generated Manuscript Draft

> This file is generated by `scripts/sync_manuscript.py`. Numeric claims are
> read from regenerated CSV/JSON artifacts and should not be edited by hand.

## Abstract

STORM-CARE-FM is a research prototype for tropical-cyclone forecasting,
physics-informed residual auditing, humanitarian proxy evaluation, and
counterfactual scenario analysis. The corrected repository reports a
validation-selected foundation checkpoint at epoch `{selected_epoch}`
(`selection_score={selection_score:.4f}`), a calibrated case-study benchmark,
corrected humanitarian proxy metrics, and module-scoped ablations. The current
Irma/Ian case-study benchmark does **not** support an all-horizon superiority
claim over Persistence: Persistence has mean 6-48 h track error
`{float(persistence_case['mean_track_km_6_48h']):.3f} km`, while GNO+DynGNN has
`{float(gno_case['mean_track_km_6_48h']):.3f} km`. Claims are therefore limited
to reproducibility, calibrated uncertainty reporting, corrected baselines, and
scientifically scoped component sensitivity.

## Results

### Forecasting

The storm-level Persistence/CLIPER table is generated from
`metrics/cliper_baseline_metrics.csv`. The neural benchmark is reported only as
an Irma/Ian ERA5-complete case study. In that case study, GNO+DynGNN beats
Transformer at 6/12/24/48 h and beats LSTM at 12/24/48 h, but it loses to
LSTM at 6 h and to Persistence at every reported case-study horizon. See
`tables/table_forecast_performance_audit.csv`.

### Calibration

Calibration tables and figures use selected checkpoint epoch `{selected_epoch}`.
The calibration consistency audit status is `{calibration_audit['status']}`.
The selected checkpoint is identified by `{foundation.iloc[0]['selection_metric']}`
with score `{selection_score:.4f}`.

### Humanitarian Proxy Metrics

Corrected Module 3 metrics are simulator-derived proxy metrics:

- Exposed-child peak MAPE: `{child_mape}`
- School disruption AUC: `{school_auc}`
- Hospital accessibility MAE: `{hospital_mae}`
- Recovery-priority Spearman: `{priority_rho}`

These results support finite synthetic-proxy evaluation, not claims of observed
real-world humanitarian accuracy.

### Ablations

Table 3 is regenerated by `scripts/run_ablations.py`. The full composite row
reports track error `{full_abl['track_error']}`, intensity error
`{full_abl['intensity_error']}`, exposure error `{full_abl['exposure_error']}`,
ranking correlation `{full_abl['ranking_correlation']}`, calibration
`{full_abl['calibration']}`, physics residual `{full_abl['physics_residual']}`,
and computational cost `{full_abl['computational_cost_s']} s`.

Graph ablations are mixed: no-transport exposure error is
`{no_transport['exposure_error']}` and ranking correlation is
`{no_transport['ranking_correlation']}`; static-graph exposure error is
`{static_graph['exposure_error']}` and ranking correlation is
`{static_graph['ranking_correlation']}`. This supports nuanced component
sensitivity, not uniform full-model superiority.

### Counterfactuals

Counterfactual outcomes are generated through learned world-model latent
rollouts. Baseline peak exposure is `{baseline_cf['peak_exposure']}`; earlier
evacuation gives `{early_cf['peak_exposure']}` and delayed evacuation gives
`{delayed_cf['peak_exposure']}` under the current 24-sequence demo.

## Discussion

The corrected repository favors defensible negative and mixed findings over
unsupported claims. The strongest current evidence is reproducibility,
leakage-controlled evaluation, corrected baseline handling, physical-consistency
improvement in the physics module, and valid synthetic-proxy humanitarian
metrics. Limitations include CPU-demo foundation training, schematic/offline
case-study maps, synthetic humanitarian labels, and a small ERA5-complete
Irma/Ian neural benchmark.
"""

    supplement = f"""# Generated Supplementary Material

## Dataset Integrity

Dataset integrity status: `{dataset_audit['status']}`.

- Storm split counts: `{dataset_audit['split_map_counts']}`
- Baseline case-study counts: `{dataset_audit['baseline_case_study_counts']}`
- Foundation record counts: `{dataset_audit['foundation_record_counts']}`
- Foundation window counts: `{dataset_audit['foundation_window_counts']}`
- Prediction rows: `{dataset_audit['prediction_rows']}`
- Prediction models: `{dataset_audit['prediction_models']}`

## Calibration Integrity

Calibration audit status: `{calibration_audit['status']}`.
Selected checkpoint epoch: `{calibration_audit['selected_epoch']}`.

## Generated Figures

- `figures/calibration.png`
- `figures/case_study/ian_noaa_track_map.png`
- `figures/case_study/ian_uncertainty_cones.png`
- `figures/case_study/ian_trajectory_errors.png`
- `figures/case_study/ian_impact_map.png`
- `figures/case_study/ian_intervention_map.png`
- `figures/case_study/ian_publication_multipanel.png`
- `figures/physics_residuals_full_vs_ablation.png`

## Generated Tables

{chr(10).join(f'- `{p}`' for p in sorted(str(p.relative_to(ROOT)) for p in (ROOT / 'tables').glob('*.csv')))}
"""

    source_files = [
        "tables/table1_track_error_vs_baselines.csv",
        "tables/table_case_study_track_error.csv",
        "tables/table_forecast_performance_audit.csv",
        "tables/table_foundation_model_training.csv",
        "tables/table_calibration_cone_coverage.csv",
        "tables/table2_humanitarian_impact.csv",
        "tables/table3_ablations.csv",
        "tables/table_counterfactual_outcomes.csv",
        "metrics/dataset_integrity/dataset_integrity_audit.json",
        "metrics/foundation/calibration_consistency_audit.json",
        "metrics/case_study/ian_case_study_manifest.csv",
    ]
    hashes = {p: _sha(ROOT / p) for p in source_files if (ROOT / p).exists()}

    experiment_log = "# Experiment Log\n\n" + "\n".join(
        f"- `{p}` sha256 `{h}`" for p, h in hashes.items()
    ) + "\n"

    reproducibility = f"""# Reproducibility Report

## Required Regeneration Commands

```bash
.venv/bin/python scripts/create_splits.py
.venv/bin/python -m model.foundation.pretrain --demo --epochs 2
.venv/bin/python benchmark.py --metrics-dir metrics
.venv/bin/python scripts/eval_humanitarian.py
.venv/bin/python -m model.counterfactual.run --demo
.venv/bin/python scripts/run_ablations.py
.venv/bin/python scripts/audit_calibration_consistency.py
.venv/bin/python scripts/audit_dataset_integrity.py
.venv/bin/python scripts/case_study_ian.py
.venv/bin/python scripts/generate_submission_outputs.py
.venv/bin/python scripts/sync_manuscript.py
```

## Integrity Status

- Dataset integrity: `{dataset_audit['status']}`
- Calibration consistency: `{calibration_audit['status']}`
- Manuscript source hashes are listed in `reports/experiment_log.md`.
"""

    change_log = """# Generated Change Log

- Replaced placeholder ablation table generation with rerunnable ablation audits.
- Regenerated NOAA-style Hurricane Ian case-study figure suite.
- Added calibration consistency audit tied to the selected foundation checkpoint.
- Added dataset integrity audit for split/sample/window counts.
- Generated synchronized manuscript and supplementary markdown from CSV/JSON outputs.
- Added experiment log and reproducibility report with source hashes.
"""

    deliverables = """# Final Deliverables Manifest

- Corrected repository code and scripts.
- Regenerated CSV files under `metrics/` and `tables/`.
- Regenerated figures under `figures/` and mirrored result folders.
- Updated generated manuscript: `manuscript/generated_manuscript.md`.
- Supplementary material: `manuscript/generated_supplement.md`.
- Experiment log: `reports/experiment_log.md`.
- Reproducibility report: `reports/reproducibility_report.md`.
- Change log: `reports/change_log.md`.
- Final validation report: `reports/validation_report.md`.
"""

    (MANUSCRIPT_DIR / "generated_manuscript.md").write_text(manuscript, encoding="utf-8")
    (MANUSCRIPT_DIR / "generated_supplement.md").write_text(supplement, encoding="utf-8")
    (REPORTS_DIR / "experiment_log.md").write_text(experiment_log, encoding="utf-8")
    (REPORTS_DIR / "reproducibility_report.md").write_text(reproducibility, encoding="utf-8")
    (REPORTS_DIR / "change_log.md").write_text(change_log, encoding="utf-8")
    (REPORTS_DIR / "final_deliverables_manifest.md").write_text(deliverables, encoding="utf-8")
    print("Generated synchronized manuscript and deliverable reports")


if __name__ == "__main__":
    main()
